CLIENT_ID: "{CLIENT_ID}"
CLIENT_SECRET: "{CLIENT_SECRET}"
ACCESS_TOKEN: "{ACCESS_TOKEN}"
SCOPE: "Files.ReadWrite.All openid User.ReadBasic.All User.ReadWrite profile email"
REDIRECT_URL: "{REDIRECT_URL}"
TENANT_ID: "{TENANT_ID}"
REFRESH_TOKEN: "{REFRESH_TOKEN}"
EXPIRY: 3599
TOKEN_TYPE: "Bearer"
UPLOAD_FOLDER_PATH: "/"
REFESH_API_ENDPOINT: "https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/token"
UPLOAD_API_ENDPOINT: "https://graph.microsoft.com/v1.0/me/drive/root:{UPLOAD_FOLDER_PATH}/{FILE_NAME}:/createUploadSession"
SHARE_API_ENDPOINT: "https://graph.microsoft.com/v1.0/me/drive/items/{UPLOADED_FILE_ID}/createLink"
GET_ITEMS_PATH_ENDPOINT: "https://graph.microsoft.com/v1.0/me/drive/root:{PATH}:/children"
GET_ITEM_API_ENDPOINT: "https://graph.microsoft.com/v1.0/me/drive/root:/{PATH}"
CREATE_FOLDER_API_ENDPOINT: "https://graph.microsoft.com/v1.0/me/drive/items/{PARENT_FOLDER_ID}/children"
DELETE_ITEM_API_ENDPOINT: "https://graph.microsoft.com/v1.0/me/drive/items/{ITEM_ID}"
MOVE_ITEM_API_ENDPOINT: "https://graph.microsoft.com/v1.0/me/drive/items/{ITEM_ID}"
COPY_ITEM_API_ENDPOINT: "https://graph.microsoft.com/v1.0/me/drive/items/{ITEM_ID}/copy"
DOWNLOAD_ITEM_API_ENDPOINT: "https://graph.microsoft.com/v1.0/me/drive/items/{ITEM_ID}/content"
FRAG_SIZE: 62259200
SHARE_BODY_JSON: "{ \"type\": \"view\", \"scope\": \"anonymous\" }"
UPLOAD_BODY_JSON: "{\"item\":{\"@microsoft.graph.conflictBehavior\":\"rename\",\"name\":\"{FILE_NAME}\"}}"
CREATE_FOLDER_BODY_JSON: "{\"name\": \"{FOLDER_NAME}\", \"folder\": {}, \"@microsoft.graph.conflictBehavior\": \"rename\" }"
MOVE_ITEM_BODY_JSON: "{ \"parentReference\": { \"id\": \"{NEW_PARENT_FOLDER_ID}\" }, \"name\": \"{NEW_ITEM_NAME}\" }"
COPY_ITEM_BODY_JSON: "{ \"name\": \"{NEW_FILE_NAME}\" }"